#!/usr/bin/ruby 

require "#{File.dirname(__FILE__)}/../../config/environment.rb"
require 'net/ldap'


def connect_to_ldap(options)
	ldap = Net::LDAP.new(options)
end

def is_empty_value?(value)
	(value.class == String and value == "") or not value or (value.class == Array and value.size == 0)
end

def remove_empty_attributes(attributes)
	# empty out 
	attributes.each do |key, value|
		if is_empty_value?(value)
			attributes.delete(key)
		end
	end
end

def create(ldap, todo, job, dn, attributes, update_failed)
	remove_empty_attributes(attributes)
	todo.emit_log(job, "inserting object: #{dn}")
	if not ldap.add(:dn => dn, :attributes => attributes)
		todo.emit_log(job, ldap.get_operation_result.message)
		todo.emit_log(job, "This corresponds to LDAP Error code #{ldap.get_operation_result.code}")
		if ldap.get_operation_result.code == 68 # that means: we have a "already exists" error, in that case we try to be "nice" and call update on that record. 
			todo.emit_log(job, "As this record seems to already exist in the database, we will try to simply update it.")
			return update(ldap, todo, job, dn, attributes, update_failed)
		end
		update_failed = true
		return false
	end
	return true
end

def update(ldap, todo, job, dn, attributes, update_failed)
	todo.emit_log(job, "updating object: #{dn}")
	attributes.each do |key, value|
		# todo.emit_log(job, "#{key} | #{value}")
		if key == :objectClass
			next
		end
		if is_empty_value?(value)
			todo.emit_log(job, "deleting #{key}")
			if not ldap.delete_attribute(dn, key)
				todo.emit_log(job, ldap.get_operation_result.message)
			end
		else
			todo.emit_log(job, "updating #{key}")
			if not ldap.replace_attribute(dn, key, value)
				update_failed = true
				todo.emit_log(job, "Error: Failed to update LDAP entry: #{ldap.get_operation_result.message}")
				return false
			end
		end
	end
	return true
end

def destroy(ldap, todo, job, dn, attributes, update_failed)
	entries = ldap.search(:base => dn) 
	if entries and entries.size > 0 
		entries.reverse.each do |entry|
			todo.emit_log(job, "deleting object: #{entry.dn}")
			if not ldap.delete :dn => entry.dn
				todo.emit_log(job, ldap.get_operation_result.message)
				if ldap.get_operation_result.code == 32 # object doesn't exist in ldap, let's be graceful and ignore that for now
					return true
				end
				update_failed = true
				return false
			end	
		end
	end
	return true
end

todo = DispatchTodoInstance.new

ldap = connect_to_ldap(todo.options[:options][:ldap])
if not ldap.bind
	puts "Error: Could not connect to LDAP server: \n#{ldap.get_operation_result.message}" 
	exit 1
end

todo.jobs.each do |job|
	#job = find_user_account(job)
	next if not job # this is not ideal yet, because this job would not succeed. 
	ldap_job = job.to_ldap(todo.options[:options])
	# this object doesn't exist anymore, some other job will take care of that ldap object.
	if (not ldap_job or not ldap_job[:dn]) 
		todo.success!(job)
	end
	dn = ldap_job[:dn]
	attributes = ldap_job[:attributes]
	# the to_ldap method in the model can overwrite the ldap operation (important in the case of m:n relationships)
	if operation = ldap_job[:options] and ldap_job[:options][:operation]
		job._operation = ldap_job[:options][:operation]
	end
	update_failed = false
	if job._operation == "create"
		next if not create(ldap, todo, job, dn, attributes, update_failed)
	elsif job._operation == "update"
		next if not update(ldap, todo, job, dn, attributes, update_failed)
	elsif job._operation == "destroy"
		next if not destroy(ldap, todo, job, dn, attributes, update_failed)
	elsif job._operation == "no_op"
		# this operation means: nothing to do for ldap. 
	else
		todo.emit_log(job, "can't handle #{job._operation} on job-id #{job.id}")
	end
	# do not return sucess! for this job if the update failed somewhere.
	if not update_failed
		todo.success!(job)
	end
end
