ARG RVM_RUBY_VERSIONS="1.9.3"
#ARG RVM_RUBY_VERSIONS="2.4 1.9.3"
FROM msati/docker-rvm
USER ${RVM_USER}
ENV RUBY=1.9
#CMD rvm ${RUBY} do irb  # TODO: this is quite surely not needed

# install packages via apt
USER root
RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
    nodejs \
    vim-tiny\
    postgresql-client\
    tmux\
    libpq-dev \
    # net-tools\
    # nodejs\
&& apt-get -q clean \
&& rm -rf /var/lib/apt/lists

# install packages/dependencies via bundler
USER ${RVM_USER}
WORKDIR /var/www/inki/
# # install inki
COPY ./Gemfile* ./
RUN gem install bundler:1.3.0  # install bundler version that works
#RUN bundler update --bundler  # does not make things better yet
RUN bundle install  # install all bundles from Gemfile[.lock]
#RUN bundler install  # does not work, but `bundle install does`


# install inki

# RUN gem install middleman     # install middleman
# RUN ls -liah                # just a test; TODO: remove   