version: "3.5"

services:
  inkidev:
    build: .
    image: inki:latest
    command: sh -c 'sleep 5; rm -f /inki/tmp/pids/server.pid; rake db:migrate && rails server -b 0.0.0.0 -p 3000'
    depends_on: 
    - inki_db
    environment:
    - RAILS_ENV=development
    - LC_ALL=C.UTF-8  # set locale
    working_dir: /inki/ 
    ports:
      - 0.0.0.0:4001:3000/tcp
    volumes:
      - type: bind
        source: .
        target: /inki


  inki_db:
    image: postgres:12.1
    restart: always
    env_file:
    - docker/inki_db.env
    volumes:
    - inki_db_volume:/var/lib/postgresql/data

volumes:
  inki_db_volume:
