FROM ruby:2.4.6

RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
    nodejs \
    vim-tiny\
    postgresql-client\
    tmux\
    # net-tools\
    # nodejs \
    # nodejs \
&& apt-get -q clean \
&& rm -rf /var/lib/apt/lists

# TODO: implement
